export const dummyData = {
  data: [
    {
      id: 0,
      contactName: "https://youtube.com",
      contactPhone: "12356648",
      companyMessage: "jfds",
      city: "vadodra",
      contactEmail: "abc@gmail.com",
      country: "India",
    },
    {
      id: 1,
      contactName: "https://youtube.com",
      contactPhone: "5646566516",
      companyMessage: "ffe",
      city: "vadodra",
      contactEmail: "abc@gmail.com",
      country: "India",
    },
    {
      id: 2,
      contactName: "https://youtube.com",
      contactPhone: "545466666465",
      companyMessage: "e56ee",
      city: "vadodra",
      contactEmail: "abc@gmail.com",
      country: "India",
    },
    {
      id: 3,
      contactName: "https://youtube.com",
      contactPhone: "54456464646",
      companyMessage: "dfkdjf",
      city: "vadodra",
      contactEmail: "abc@gmail.com",
      country: "India",
    },
    {
      id: 4,
      contactName: "https://youtube.com",
      contactPhone: "545646646",
      companyMessage: "ejuer",
      city: "vadodra",
      contactEmail: "abc@gmail.com",
      country: "India",
    },
    {
      id: 5,
      contactName: "https://youtube.com",
      contactPhone: "5565565656",
      companyMessage: "jiouio",
      city: "vadodra",
      contactEmail: "abc@gmail.com",
      country: "India",
    },
    {
      id: 6,
      contactName: "https://youtube.com",
      contactPhone: "787984846",
      companyMessage: "jjl",
      city: "vadodra",
      contactEmail: "abc@gmail.com",
      country: "India",
    },
    {
      id: 7,
      contactName: "https://youtube.com",
      contactPhone: "545645646",
      companyMessage: "uiouioer",
      city: "vadodrai",
      contactEmail: "abc@gmail.com",
      country: "India",
    },
    {
      id: 8,
      contactName: "https://youtube.com",
      contactPhone: "879889899",
      companyMessage: "tuioer",
      city: "vadodra",
      contactEmail: "abc@gmail.com",
      country: "India",
    },
    {
      id: 9,
      contactName: "https://youtube.com",
      contactPhone: "4678789799",
      companyMessage: "iwpr",
      city: "vadodra",
      contactEmail: "abc@gmail.com",
      country: "India",
    },
    {
      id: 10,
      contactName: "https://youtube.com",
      contactPhone: "1231345646",
      companyMessage: "ieuroi",
      city: "vadodra",
      contactEmail: "abc@gmail.com",
      country: "India",
    },
  ],
};
